# Generated by Django 5.2.3 on 2025-08-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_auther_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
